Handle the case where the domain or header domain is malformed
dhs-ncats/trustymail_reporter pull request #64
Opened 2022-01-24 16:22 UTC by jsf9k

## 🗣 Description ##

This pull requests modifies the code to handle the case where the domain or header domain is malformed.

## 💭 Motivation and context ##

There was a case this past weekend where an HHS header domain was malformed such that the `get_public_suffix()` call returned `None`.  With these changes the code will handle such cases without crashing and will print out a helpful logging message.

## 🧪 Testing ##

All `pre-commit` hooks pass.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - _eschew scope creep!_
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [ ] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [ ] Finalize version.

## ✅ Post-merge checklist ##

- [ ] Add a tag.

2022-01-25 15:38 UTC, dav3r approved these changes
Good sleuthing, nice fix and cleanup! 🔎 👍

2022-01-25 16:17 UTC, mcdonnnj requested changes
Makes sense, but from the [Python `logging` documentation](https://docs.python.org/3/library/logging.html#logging.Logger.warning):

> Note
>
> There is an obsolete method `warn` which is functionally identical to `warning`. As `warn` is deprecated, please do not use it - use `warning` instead.

2022-01-25 16:17 UTC, mcdonnnj commented on src/report/generate_trustymail_report.py
> +                                    logging.warn(
```suggestion
                                    logging.warning(
```

2022-01-25 16:17 UTC, mcdonnnj commented on src/report/generate_trustymail_report.py
> +                                    logging.warn(
```suggestion
                                    logging.warning(
```

2022-01-25 16:17 UTC, mcdonnnj commented on src/report/generate_trustymail_report.py
> +                                    logging.warn(
```suggestion
                                    logging.warning(
```

2022-01-25 16:17 UTC, mcdonnnj commented on src/report/generate_trustymail_report.py
> +                                    logging.warn(
```suggestion
                                    logging.warning(
```

2022-01-25 20:50 UTC, mcdonnnj approved these changes

2022-01-27 22:24 UTC, dav3r approved these changes
👍 👍

2022-01-28 17:22 UTC, mcdonnnj approved these changes
`:=` :godmode:

2022-01-28 17:35 UTC, merged